# This is a basic workflow to help you get started with Actions

# Nombre de nuestro Workflow 
name: CI

# Sirve para decirle en qué eventos queremos que se ejecute nuestro workflow
on:
  # Se va a ejecutar las tareas cuando se haga un push en la rama main
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Si queremos ejecutar un Workflow manualmente
  workflow_dispatch:

# Serie de tareas que se van a ejecutar en nuestro workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # Variables de entorno que se van a utilizar en nuestro workflow
    env:
      plattform: aws
      region: us-central1
      account: 123456789

      # Asignamos unos secrets a nuestras variables de entorno del Workflow
      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    # Nos crea una maquina virtual con el sistema operativo ubuntu para ejecutar las tareas de nuestro workflow
    runs-on: ubuntu-latest

    # Secuencia de pasos que se van a ejecutar en nuestro workflow
    steps:
      # Nombre nuestra primera tarea
      - name: "Display Message"
        # Comando que se va a ejecutar en nuestra tarea
        run: echo "Hello World"

      # Nombre nuestra segunda tarea
      - name: "Mostrando variables de entorno"
        # Comando que se va a ejecutar en nuestra tarea || Esta lo que hace es mostrar las variables de entorno que hemos definido en nuestro workflow
        # Se coloca un "|" para que se pueda ejecutar más de un comando en un solo run. Se conoce como PIPE
        run: |
          echo "Esto es el valor de plattform: ${{env.plattform}}"
          echo "Esto es el valor de region: ${{env.region}}"
          echo "Esto es el valor de account:: ${{env.account}}"

      # Nombre nuestra tercera tarea
      - name: "Utilizando los condicionales"
        # Se pueden utilizar condicionales para ejecutar tareas en nuestro workflow si se cumple una condición
        # En este caso se va a ejecutar si la variable de entorno plattform es igual a GCP
        if: ${{env.plattform == 'GCP'}}
        run: |
          echo "Esto es el valor de plattform: ${{env.plattform}}"
          echo "Esto es el valor de region: ${{env.region}}"
          echo "Esto es el valor de account:: ${{env.account}}"

      # Nombre nuestra cuarta tarea
      - name: "Mostrando varibales de entorno por defecto de GitHub"
        # Se pueden utilizar las variables de entorno por defecto de GitHub para mostrar información de los eventos que se han ejecutado
        # Las variables de GitHub se colocan con el prefijo GITHUB_ y en mayúsculas y no se necesita colocarles el {{env.}}
        run: |
          echo "Evento: ${{toJson(github.event)}}"
          echo "GitHub Actor: $GITHUB_ACTOR" 
          echo "GitHub Repository: $GITHUB_REPOSITORY"
      
      # Nombre nuestra quinta tarea
      - name: "Mostrando los secrets de GitHub"
        run: |
          echo "Username: ${{env.username}}"
          echo "Password: ${{env.password}}"
